### PR TITLE
auto-cf: support modpack zips using IMPLODE compression method

### PR DESCRIPTION
**Pull request by itzg**
Resolves https://github.com/itzg/docker-minecraft-server/issues/2645

Observed with https://www.curseforge.com/minecraft/modpacks/age-of-engineering/files/2503175

Also
- adds and uses by default the PlayerDB API for resolving whitelist and ops. Pulls in https://github.com/itzg/mc-image-helper/pull/393

### CODE REVIEW

**Comment by NotJohnAfterall** [comment]
Thanks, i updated the image but now it throws an timed out error to the api server: 

[init] Running as uid=1000 gid=1000 with /data as 'drwxr-xr-x 5 1000 1000 4096 Feb  8 14:15 /data'                                                                                                                                           [mc-image-helper] 21:26:56.551 INFO  : Processing modpack 'Age of Engineering-1.1.2.zip' (age-of-engineering) @ 263897:2503175                                                                                                               
[mc-image-helper] 21:27:26.673 WARN  : [2eb28e2b-1, L:/<here is some ip 1> - R:api.curseforge.com/<here is some ip 2>] The connection observed an error                                                                                              io.netty.handler.timeout.ReadTimeoutException: null                                                                                                                                                                                          [mc-image-helper] 21:27:26.674 WARN  : [b856eba3-1, L:/<here is some ip 1> - R:api.curseforge.com/<here is some ip 2>] The connection observed an error                                                                                              io.netty.handler.timeout.ReadTimeoutException: null                                                                                                                                                                                          [mc-image-helper] 21:27:26.679 ERROR : Operator called default onErrorDropped                                                                                                                                                                io.netty.handler.timeout.ReadTimeoutException: null                                                                                                                                                                                          [mc-image-helper] 21:27:26.684 ERROR : 'install-curseforge' command failed. Version is 1.37.11                                                                                                                                               io.netty.handler.timeout.ReadTimeoutException: null                                                                                                                                                                                          [init] ERROR failed to auto-install CurseForge modpack

idk if this is just a some other server issue, but sadly it doesnt work again :)

**Comment by itzg** [comment]
I'm thinking CurseForge was having some problems on their end. I noticed a lot of the image variants failed to build with similar error messages.

**Comment by NotJohnAfterall** [comment]
Yeah i thought same thing, i will wait till tomorrow and see if anything will change.

**Comment by itzg** [comment]
This build seems to be running better now

https://github.com/itzg/docker-minecraft-server/actions/runs/7835950318

**Comment by NotJohnAfterall** [comment]
Ok, so i tried to remove docker image and run the server again and finally it works. Thank you so much for quick responses and very fast fix of the issue. I didn't expect this to be resolved so quickly, so thank you!

**Comment by NotJohnAfterall** [comment]
If I may ask, I can't set auto-pause, I found this thread  #1636 , but I don't know if I'm completely stupid, but I can't find how to fix it. I have the same problem as the guy who described it there but I really don't know where the problem is. Sorry for asking such a stupid question.

**Comment by itzg** [comment]
@NotJohnAfterall did you happen to manually change the server port in server.properties? I noticed in your original issue description you're using port 25665 rather than the default 25565. If that's the case then set this to match https://docker-minecraft-server.readthedocs.io/en/latest/configuration/server-properties/#server-port

In case this helps

https://raw.githubusercontent.com/itzg/docker-minecraft-server/master/notes/container-network-namespaces.drawio.png

**Comment by NotJohnAfterall** [comment]
I've changed the port in server server.properties to 25665 and changed in docker-compose.yml server ports to be 25665:25565 (before i had server.properties to 25665 and docker-compose.yml server ports to be 25665:25665) , based on the image you sent. And it still doesnt work. The reason why i change ports is that, i have multiple servers running (this is second one :) )

**Comment by itzg** [comment]
> The reason why i change ports is that, i have multiple servers running (this is second one :) )

That's the point I'm making with the image. You don't need to change the ports except for the one value that is the host port in the mapping. Leave all the other ports at 25565.

**Comment by NotJohnAfterall** [comment]
Oh, i see. I did that and now it works. Thank you so much. Have a awesome day :)

**Pull request merged**
