### PR TITLE
Add GraalVM CE support

### PR DESCRIPTION
**Pull request by NoaHimesaka1873**
Unfortunately, GraalVM EE needs complex setup to build (you need to register to Oracle Container Registry and log in) so only CE for now. Build tested.

RELATED: itzg/docker-minecraft-server#1252

### CODE REVIEW

**Review by itzg — COMMENTED** [review]
Awesome! Works great. If you could add the two new line items to https://github.com/itzg/docker-minecraft-server#running-minecraft-server-on-different-java-version then this is ready to merge.

**Comment by NoaHimesaka1873** [comment]
@itzg Just did it!

**Review by itzg — APPROVED** [review]
Thanks!

**Comment by NoaHimesaka1873** [comment]
@itzg Hmm... seems like we have to delete check for ZSTD for Oracle Linux 8-based images. tar on OL8 seems like it can't handle zstd. Works on my production OL9 funnily.

**Comment by itzg** [comment]
Weird, the PR testing build should have flagged that. I/you can use the "require" mechanism to skip that test for graal builds.

**Comment by itzg** [comment]
...ah, PR build only considers the "latest" base image. The build-time trade off is awkward with PR builds.

**Pull request merged**
