### PR TITLE
Add Discord Release Notification

### PR DESCRIPTION
**Pull request by rhullah**
Add an on-publish step to send a Discord notification when a release is published.

Additionally:
- removed old workflow names
- format the args a little nicer
- remove the redundant expression syntax on `if:`

I assume this will go to the `#ci` channel in Discord. Felt like `#releases` would make more sense, but I'm assuming that's just official Minecraft releases and integrated via Discord.

### CODE REVIEW

**Review by itzg — APPROVED** [review]
Looks great, thanks! Yes, in hindsight the releases channel would have been for set aside for image releases and I suppose is could be arranged as such. Let's keep it all in the ci channel until it bugs us and can split things out.

**Comment by itzg** [comment]
That's a little annoying that Discord created embeds for the linked PRs. I wonder if surrounding them in angle brackets would suppress that?

https://discord.com/channels/660567679458869252/927361063572365352/1181809421060423770

Not a big deal though.

**Comment by rhullah** [comment]
Man...you just said everything I was typing up! 😆 Yeah, only options I can think of would be to either tweak the release body to surround the links in `<>`, or see if that Action has any sort of option to to it itself. Do you have any thoughts?

**Comment by rhullah** [comment]
Hmm, also noticed the HTML comment rendered in the Discord message too. Which means that'd need to be stripped out. I'm playing with something.

**Comment by itzg** [comment]
Yeah, I'm actually hoping that GitHub action or an alternate one has an option to escape links in the body or disable embeds when posting. I vaguely remember that's an API option.

**Pull request merged**
