### PR TITLE
possible solution to deploy to both dockerhub and ghcr

### LINKED ISSUE #1444: Release Docker Images on Github's Container registry
### Enhancement Type

A completely new feature

### Describe the enhancement

I didn't see a previous issue, but apologizes if I missed it. 

I was wondering if it would be a good idea to also have the docker images available via [Github's Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

This is something that I could take on if it is a good idea.

### PR DESCRIPTION
**Pull request by camalot**
I am not able to test this AFAIK because of permissions and such, but this should log in to both dockerhub and ghcr, and add image tags for both dockerhub and ghcr. 

Closes #1444 and #2009

### CODE REVIEW

**Review by itzg — APPROVED** [review]
The changes look right to me. I'll try to lookup how I did my initial testing of the image publishing 😀.

**Comment by itzg** [comment]
...oh, I remember now. The build triggers inlcude branches that start with `test/`.

**Comment by itzg** [comment]
As far as you testing it, I think it'll work for a non-PR'ed branch that starts with `test/` as long as you have the Docker hub credentials declared in your repo actions secrets.

**Comment by camalot** [comment]
I will see if i can get it to test when I take lunch.

**Comment by camalot** [comment]
i see in the build-multiarch a reference to MODS_FORGEAPI_KEY. can you point me to where I can request a key? I am creating a `test/` branch to make sure this all works.

**Comment by camalot** [comment]
Ok, i was going to try my CF Key. thanks.

**Comment by itzg** [comment]
...and now that I rediscovered that, makes me realize I could be re-enabling the build time test for auto CurseForge by re-mapping that variable

**Comment by itzg** [comment]
If you want to include that with your PR it would be a copy of this line

https://github.com/itzg/docker-minecraft-server/blob/0d5e44a3387bfd5462342e5729351b719c357178/.github/workflows/build-multiarch.yml#L152

but with CF_API_KEY being the resulting variable.

**Comment by camalot** [comment]
ive got a test/ branch running now with those changes, since this PR is open on the non-test branch, if it is successful, I will merge those changes back in to this branch, and will reference the test branch action runs.

**Comment by camalot** [comment]
https://github.com/camalot/docker-minecraft-server/actions/runs/4576294508 current run

**Comment by camalot** [comment]
Login for GHCR was successful for all platforms. as was the build. the build and push was also successful, but doesn't actually push (so it isn't fully tested with the `github.token`) since it isn't running from a PR to master.

**Comment by camalot** [comment]
I have a feeling that using `github.token` isn't going to have access to push to GHCR. I haven't tested this feeling yet though.

**Comment by itzg** [comment]
I'm sorry that I forgot about this PR. Later today I'll either do a quick test branch build or just merge and tweak configs from there if needed.

**Comment by itzg** [comment]
Pushed some fixes to the build to handle test/* branches. Apparently I broke it was back when I switched to matrix builds.

**Comment by camalot** [comment]
I see that the push to ghcr.io is failing with a 500. i may modify the job that pushes to have it push to my docker hub and ghcr. see if i can reproduce it.

**Comment by itzg** [comment]
That would be great. Using the `github.token` way it was mostly 500's:

https://github.com/itzg/docker-minecraft-server/actions/runs/4600691357

Using `secrets.GITHUB_TOKEN`, which I just pushed, it was a mix of success and 403's

https://github.com/itzg/docker-minecraft-server/actions/runs/4603497390/jobs/8133557812

I'm suspecting there is a rate limit on GHCR publish operations, where 14 concurrent ones probably exceeds that.

**Comment by camalot** [comment]
https://github.com/camalot/docker-minecraft-server/pkgs/container/minecraft-server

I changed the action settings to read/write and it pushed to ghcr for my fork, and my docker hub

image

**Comment by camalot** [comment]
https://github.com/camalot/docker-minecraft-server/tree/test/ghcr-publish

this is the branch that pushed.

**Comment by camalot** [comment]
Obviously i had to change the build-publish workflow to push to on a less restrictive criteria. but that is the only thing that should have been changed compared to what i pushed to this branch.

**Comment by itzg** [comment]
> i had to change the build-publish workflow to push to on a less restrictive criteria

Hmm, I had the workflow settings like you screenshot'ed above, so I'm wondering what you mean by these workflow changes?

The mix of success and 403's (and 500s) was very odd though. It's like the permissions are right, but something sporadically fails.

**Comment by camalot** [comment]
This is what i changed in my `test/` branch to force it to push for me. everything else in my branch should be in-line with the rest of the changes in this PR. 

image


Actually, im not 100% that I pulled in all the changes you pushed to this branch. Let me do that and run it again.

**Comment by itzg** [comment]
Can you point me to the latest build that went through for you? I'll put my test branch back to `github.token` and see how it is now.

**Comment by camalot** [comment]
the run https://github.com/camalot/docker-minecraft-server/actions/runs/4613328275

the branch https://github.com/camalot/docker-minecraft-server/tree/test/ghcr-publish

**Review by itzg — APPROVED** [review]

**Pull request merged**
