### PR TITLE
Fixing AUTOPAUSE on Raspberry Pi 4s

### PR DESCRIPTION
**Pull request by ErstBlack**
Adding net-tools, replacing killall with pkill, and replacing ps -a with ps -ax

### CODE REVIEW

**Comment by ErstBlack** [comment]
So it looks like there's still an issue with the resume functionality, but that seems more to do with the fact that there's a handful of interfaces which the [java_clients_connected](https://github.com/itzg/docker-minecraft-server/blob/master/files/autopause/autopause-fcns.sh#L19) call is missing out on, probably because I'm running it in a stack rather than a standalone container.

**Review by itzg — APPROVED** [review]
LGTM. @Oekn5w , any requests?

**Comment by Oekn5w** [comment]
also fails to resume for me.
To the matter of the PR: missed a `ps` in `health.sh` and `killall` in `files/sudoers-mc` , `pkill`resides in `/usr/bin/pkill`

**Comment by Oekn5w** [comment]
@ErstBlack replacing `/sbin/su-exec` with `gosu` fixes also the resuming part of the functionality.

**Comment by Oekn5w** [comment]
looks good, thanks for troubleshooting and fixing this

**Review by itzg — APPROVED** [review]

**Pull request merged**
