### PR TITLE
Update cf-exclude-include.json

### PR DESCRIPTION
**Pull request by LeaderbotX400**
Add: iris-flywheel-compat

### CODE REVIEW

**Review by itzg — CHANGES_REQUESTED** [review]
Thanks! 

I hate to ask, but since the list is pretty long, can you add that new entry in alphabetical order (after "ignitioncoil")?

**Comment by LeaderbotX400** [comment]
> Thanks!
> 
> I hate to ask, but since the list is pretty long, can you add that new entry in alphabetical order (after "ignitioncoil")?

yea sure

**Review by itzg — APPROVED** [review]
Thanks for the quick update.

**Comment by LeaderbotX400** [comment]
> Thanks for the quick update.

No problem. Always happy to help

**Comment by itzg** [comment]
FYI, build failure is a random network thing

**Pull request merged**
