### PR TITLE
Remove LoliServer from README.md

### PR DESCRIPTION
**Pull request by khankul**
LoliServer is dead per #1622

### CODE REVIEW

**Comment by itzg** [comment]
> LoliServer is dead per #1622

Not that I was aware. Last comment I noted was that it **moved** 

https://github.com/itzg/docker-minecraft-server/issues/1622#issuecomment-1193202607

**Comment by khankul** [comment]
There's a latest build link in scripts/start-deployLoliserver, but it returns 404, and its builds seem to be no longer available. So I assumed since the project was moved and renamed, the old version of it is dead.

**Comment by itzg** [comment]
So the link needs to change to pull from https://github.com/Luohuayu/CatServer/releases

**Comment by khankul** [comment]
But, there already is an option to install CatServer.
Also, judging by https://github.com/Luohuayu/CatServer/blob/1.16.5/docs/README_EN.md,
"It will now continue to be maintained as a fork of LoliServer"
so the devs treat it as a fork rather than renamed project.

**Comment by itzg** [comment]
Oh, sorry, I didn't even make the connection. These forks of forks of forks are very confusing.

**Review by itzg — COMMENTED** [review]
Can you also remove the code for it
- delete https://github.com/itzg/docker-minecraft-server/blob/master/scripts/start-deployLoliserver
- remove the entry from https://github.com/itzg/docker-minecraft-server/blob/master/scripts/start-configuration

**Review by itzg — APPROVED** [review]

**Pull request merged**
