### PR TITLE
if REMOVE_OLD_MODS = true redownload plugins

### PR DESCRIPTION
**Pull request by boyphongsakorn**
if REMOVE_OLD_MODS is True
set installedVersion = 0.0.0

### CODE REVIEW

**Comment by boyphongsakorn** [comment]
> Please provide a description on PRs. I can't review this until I know what problem was being solved.

ok, i add it.

**Comment by boyphongsakorn** [comment]
> why are you proposing this change? Container config attempted? Expected results? Opening an issue first for discussion would have been good.

when i environment variables `REMOVE_OLD_MODS` is `True` or manually remove plugin, it remove plugin but not redownload plugins because `version meta data is still` and it see same version in spigot/spiget, it will not redownload

**Comment by itzg** [comment]
Thank you. That is a good reason for the change.

**Review by itzg — APPROVED** [review]
Sorry for the delay getting back to this. The changes look great for the problem solved.

**Pull request merged**
