### PR TITLE
Add SERVER_HOST Environment in mc-monitor command

### PR DESCRIPTION
**Pull request by felipepasc**
Added a variable for mc-monitor to recognize other addresses if network mode is host

### CODE REVIEW

**Review by itzg — COMMENTED** [review]
Thanks! It would be great to document it too -- perhaps a sentence section added to https://github.com/itzg/docker-minecraft-server/blob/master/docs/configuration/misc-options.md

**Comment by felipepasc** [comment]
I added the requested docs!

**Review by itzg — APPROVED** [review]
Thanks!

**Comment by felipepasc** [comment]
When this is approved, does it already update the docker image?

**Comment by itzg** [comment]
Yep, most of the builds just finished

https://github.com/itzg/docker-minecraft-server/actions/runs/9392759483

**Pull request merged**
