### PR TITLE
Added support for Modrinth modpacks as a server type

### LINKED ISSUE #1574: Support for Modrinth ModPacks
### Enhancement Type

New server type

### Describe the enhancement

Currently, Modrinth mod packs are still in alpha, but as far as I can tell the format seems to be stable.
It is described here: https://docs.modrinth.com/docs/modpacks/format_definition/

### PR DESCRIPTION
**Pull request by itzg**
Resolves #1574 
Pulls in
- https://github.com/itzg/mc-image-helper/pull/217
- https://github.com/itzg/mc-image-helper/pull/218

### CODE REVIEW

**Comment by itzg** [comment]
@GeoDerp would be glad to get any review comments you have on this.

**Comment by GeoDerp** [comment]
> @GeoDerp would be glad to get any review comments you have on this.

Looks good @itzg , considering its 11:29pm here Ill have a better look tomorrow morning if you like, when im awake. 😂

for the [README.md](https://github.com/itzg/docker-minecraft-server/pull/2128/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R596-R615)
did you want to talk about: 
- MODRINTH_FORCE_MODLOADER_REINSTALL
- MODRINTH_FORCE_SYNCHRONIZE
?

**Comment by itzg** [comment]
Thanks! I might go ahead and merge in a little while, but I'll be glad to address any follow up comments. 

As for those variables/arguments, I later realized that those are not useful like they were with AUTO_CURSEFORGE. So, to keep the docs simple and to the point, I'll wait until later if/when they need to be covered.

**Comment by GeoDerp** [comment]
tweaked the ARM Azure Template to some support the modrinth modpack command. Have to look into it more deeply the next few days but im currently having some errors like: `me.itzg.helpers.http.FailedRequestException: HTTP request of https://api.modrinth.com/v2/version/2.2.0 failed with 400 Bad Request: Fetching object content`

https://github.com/GeoDerp/azure-minecraft-server/tree/modrinth

**Comment by itzg** [comment]
@GeoDerp did you happen to set version ID to "2.2.0"? If so, that'll be the problem since it has to be the ID and not the name (at this time). I could probably enhance that since the version page URL support will pick out the version by name.

**Comment by itzg** [comment]
...actually, give the latest image a try since #2130 allows for ID, name or number to be provided for the version. Also, the variable is now `MODRINTH_VERSION`.

**Pull request merged**
