### PR TITLE
Fix/825 (part 1): specify SPIGET resource version

### LINKED ISSUE #825: Support Spiget resource versions
I'm thinking the format `RESOURCE_ID:VERSION_ID` will work without much change to the existing feature.
The version ID should assume latest _(filtering by the Minecraft version?)_ if not specified.

```
-e SPIGET_RESOURCES=9089:367353,34315,28140:388301
```

Another good feature would be printing a summary of plugins/versions on start & if the specified version is not up-to-date.
I would perhaps consider adding another feature to check the hash of the existing plugins to verify if they're already downloaded (#978?)

### PR DESCRIPTION
**Pull request by DanielRamp**
allows to specify which version of the SPIGET resource to download
probably fixes #825 partially

Sorry for first contribution bug (#981), this time it won't have `${$var}` in it :/, but I still didn't build the docker image from my code, so not fully tested.

### CODE REVIEW

**Comment by itzg** [comment]
Sorry it took me a while to get back to this. The code changes look good...

> I still didn't build the docker image from my code, so not fully tested.

...but I really need you to build the image and test since I have been able to setup very little CI testing.

**Comment by DanielRamp** [comment]
```
$ curl -I https://api.spiget.org/v2/resources/9089/download | grep location
location: https://cdn.spiget.org/file/spiget-resources/9089.zip
```

```
$ curl -I https://api.spiget.org/v2/resources/9089/versions/latest/download | grep location
location: https://spigotmc.org/resources/9089/download?version=367353
```

The spiget api returns diffrent download address if a specific version is requested.
That doesn't seem bad first but if you try **curl'ing spigotmc.org** then I get http error **503 from Cloudflare** servers.

**Comment by itzg** [comment]
> The spiget api returns diffrent download address if a specific version is requested.

Yeah and same useless response from `curl -I https://api.spiget.org/v2/resources/9089/versions/367353/download | grep location`. Avoiding the SpigotMC CloudFlare is whole point of using the Spiget API, so an extra shame they broke this.

**Comment by DanielRamp** [comment]
I think we can't do anything to solve this, except hoping/helping spiget fixing it.
I created a issue in their issue collection [here](https://github.com/SpiGetOrg/Spiget/issues/41).

**Comment by InventivetalentDev** [comment]
> Avoiding the SpigotMC CloudFlare is whole point of using the Spiget API, so an extra shame they broke this.  

Nothing was broken, it has always been this way.

**Comment by itzg** [comment]
My apologies, I had not used that particular endpoint previously so my assumption that that it broke since initial deployment was not valid.

All I know is that the requested feature #825 is blocked by an inconsistent redirect outcome of the version-qualified and non-qualified `resources` endpoints:

```
$ curl -I https://api.spiget.org/v2/resources/9089/download           
HTTP/2 302 
date: Fri, 30 Jul 2021 19:12:07 GMT
content-type: text/plain; charset=utf-8
content-length: 75
location: https://cdn.spiget.org/file/spiget-resources/9089.zip
cf-ray: 6770e58e5ce5ec11-ATL
access-control-allow-origin: *
vary: Accept, Accept-Encoding
cf-cache-status: BYPASS
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-powered-by: Express
x-spiget-file-source: cdn
x-spiget-server: nougat
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=9GpDdPaVdNiZmvy9LtbMz89TTtHx8W2KtJgvRT4Fi9gMGbDV5pifg6D65GXycbWI5qmrqULiQkUqnFvSgiDsgFcsunTl%2F8ZNtVK57VMIJzWIPp5AyIzi1eVdvxMG%2FHM%2F"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare

$ curl -I https://api.spiget.org/v2/resources/9089/versions/367353/download
HTTP/2 302 
date: Fri, 30 Jul 2021 19:13:06 GMT
content-type: text/plain; charset=utf-8
content-length: 81
location: https://spigotmc.org/resources/9089/download?version=367353
cf-ray: 6770e6fcad67f325-ATL
access-control-allow-origin: *
vary: Accept, Accept-Encoding
cf-cache-status: BYPASS
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-powered-by: Express
x-spiget-server: mango
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=9pEVx2H9oXY3KYYISRrsHFqHF3Y%2BMA366291Yam4ziLt1IqhHoSF%2B%2F6AtYKCawbt54NzG4D0NCBaESaeEhuBxlYu29subl4Anrv4wHgJ%2BGDiamPZYgs92h5PmvasxXbC"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
```

and then following the redirect in the second:
```
HTTP/2 503 
date: Fri, 30 Jul 2021 19:18:35 GMT
content-type: text/html; charset=UTF-8
x-frame-options: SAMEORIGIN
permissions-policy: accelerometer=(),autoplay=(),camera=(),clipboard-read=(),clipboard-write=(),fullscreen=(),geolocation=(),gyroscope=(),hid=(),interest-cohort=(),magnetometer=(),microphone=(),payment=(),publickey-credentials-get=(),screen-wake-lock=(),serial=(),sync-xhr=(),usb=()
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
expires: Thu, 01 Jan 1970 00:00:01 GMT
cf-request-id: 0b9a73b9b400000fec1b8a7000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=tsdiA6BXfrYdQkFXOmlj8QkYBpoh4137S%2FvmVVq6sgVtso5AinLV3M1moIkBvVmE3fH%2FplZSw201usXN2X5mB9ET%2FoAnVdkuHjLRAz5%2F%2Bj0IT5nxFGngG32f3GyikQ%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6770ef0929b90fec-ATL
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400, h3=":443"; ma=86400
```

**Comment by InventivetalentDev** [comment]
they're two completely different api endpoints and that's also stated in the documentation. 
see https://github.com/SpiGetOrg/Spiget/issues/41#issuecomment-890046267 as well

**Comment by DanielRamp** [comment]
This is a (somewhat) old thread. To keep the repository clean I close it now with this comment since I don't think there is anything we or spiget could really do about it.

_Feel free to reopen it._

**Pull request closed without merging**
