### PR TITLE
Fix typo in deployAutoCF-Script

### PR DESCRIPTION
**Pull request by denizkoekden**
You made a little typo in your last commit which broke the container with existing Compose-Files. This fixes it.

### CODE REVIEW

**Review by itzg — COMMENTED** [review]
That's not a typo. Please provide an example that doesn't work.

**Comment by itzg** [comment]
FYI, [info on that syntax](: "${CF_EXCLUDE_INCLUDE_FILE=https://raw.githubusercontent.com/itzg/docker-minecraft-server/master/files/cf-exclude-include.json}"
).

Please clarify what is not working. Have you run with `DEBUG: "true"` to investigate the invocation of mc-image-helper?

**Comment by itzg** [comment]
Fix is on the way https://github.com/itzg/mc-image-helper/pull/172

**Comment by denizkoekden** [comment]
Yes no problem. This seemed to be the most obvious thing to me. But seeing the commit in mc-image-helper that makes more sense. Will try it as soon as the image is deployed on docker hub. Thanks!

**Comment by itzg** [comment]
To give some context, that was one of the rare times that syntax is useful since I needed to differentiate an unset value vs a value set with an empty string to allow for disabling the default file usage.

**Comment by itzg** [comment]
Image build is in progress: https://github.com/itzg/docker-minecraft-server/actions/runs/4479470997

**Comment by denizkoekden** [comment]
Its working now btw :) Thanks

**Pull request closed without merging**
