### PR TITLE
Add helm charts

### PR DESCRIPTION
**Pull request by sfxworks**
As a submodule since I plan to do a lot with prow and CI.

Relates to #362

- k8s deployment by referencing simplified values
- Compatible with helm 3 
- Deploys service type NodePort and encourages SRV records instead of 1 server per IP models
- Will include future updates like SSH and Web for the Dynmap / web of things 

```
2m41s       Normal    SuccessfulCreate       statefulset/chart-1584956837                 create Pod chart-1584956837-0 in StatefulSet chart-1584956837 successful
<unknown>   Normal    Scheduled              pod/chart-1584956837-0                       Successfully assigned test/chart-1584956837-0 to a6
2m40s       Normal    Pulled                 pod/chart-1584956837-0                       Container image "docker.io/itzg/minecraft-server:adopt13" already present on machine
2m40s       Normal    Created                pod/chart-1584956837-0                       Created container chart-1584956837
2m40s       Normal    Started                pod/chart-1584956837-0                       Started container chart-1584956837
101s        Warning   Unhealthy              pod/chart-1584956837-0                       Readiness probe failed: server not ready localhost:25565
<unknown>   Normal    Scheduled              pod/chart-1584956837-connection-test-flk9x   Successfully assigned test/chart-1584956837-connection-test-flk9x to a6
29s         Normal    Pulling                pod/chart-1584956837-connection-test-flk9x   Pulling image "itzg/mc-monitor:0.5.0"
22s         Normal    Pulled                 pod/chart-1584956837-connection-test-flk9x   Successfully pulled image "itzg/mc-monitor:0.5.0"
22s         Normal    Created                pod/chart-1584956837-connection-test-flk9x   Created container main
22s         Normal    Started                pod/chart-1584956837-connection-test-flk9x   Started container main
30s         Normal    SuccessfulCreate       job/chart-1584956837-connection-test         Created pod: chart-1584956837-connection-test-flk9x
```
```
PS C:\Users\shaba\Documents\git\mcsh-charts\server-deployment> helm install . --wait --generate-name
NAME: chart-1584956837
LAST DEPLOYED: Mon Mar 23 05:47:18 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
PS C:\Users\shaba\Documents\git\mcsh-charts\server-deployment> helm test chart-1584956837
NAME: chart-1584956837
LAST DEPLOYED: Mon Mar 23 05:47:18 2020
NAMESPACE: test
STATUS: deployed
REVISION: 1
TEST SUITE:     chart-1584956837-connection-test
Last Started:   Mon Mar 23 05:49:29 2020
Last Completed: Mon Mar 23 05:49:43 2020
Phase:          Succeeded
```

### CODE REVIEW

**Comment by sfxworks** [comment]
That will take some time since I'd have to alter it a bit more/await helm/repo/charts for PR approval, but I could do that! Sounds like a plan.

**Comment by itzg** [comment]
Thanks. If it helps I could create a starter README in the examples directory that in turn can be referenced from the top of the main README. I think a small paragraph with a link to your repo https://github.com/mcserverhosting-net/charts would be sufficient since you then provide all the helm repo operations a user would need there.

**Comment by sfxworks** [comment]
That would be great! I have the week off so I'm planning to continue working on the charts throughout.

**Comment by itzg** [comment]
Can you see if https://github.com/itzg/docker-minecraft-server/pull/461 works for you?

**Comment by itzg** [comment]
I am going to close this since official Helm charts have since been moved to https://github.com/itzg/minecraft-server-charts

**Pull request closed without merging**
