### PR TITLE
Fix Forge download

### LINKED ISSUE #889: Forge download issue.
I was checking out the url for the forge installer and it seems to be behind a shortner and in a different syntax for the domain. 
https://adfoc.us/serve/sitelinks/?id=271228&url=https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-installer.jar.  The url is able to be stripped and link after the ampersand will work this syntax just needs to be reflected in the shell script.

logs:
```
minecraft    | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x    2 1000     1000          4096 May 23 23:40 /data'
minecraft   | [init] Resolved version given 1.12.2 into 1.12.2
minecraft    | [init] Resolving type given FORGE
minecraft    | [init] Checking Forge version information.
minecraft    | [init] Downloading 1.12.2-14.23.5.2854-1.12.2
minecraft    | [init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854-1.12.2/forge-1.12.2-14.23.5.2854-1.12.2-installer.jar
minecraft   | curl: (6) Could not resolve host: files.minecraftforge.net
minecraft    | [init] ...trying http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-installer.jar
minecraft    | curl: (6) Could not resolve host: files.minecraftforge.net
minecraft    | [init] Unable to compute URL for 1.12.2-14.23.5.2854-1.12.2
```

docker-compose.yml configuration
```
version: "3"
services:
  minecraft:
    container_name: minecraft
    image: itzg/minecraft-server:java8
    tty: true
    stdin_open: true
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      VERSION: 1.12.2
      TYPE: FORGE
      FORGEVERSION: 14.23.5.2854
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
    volumes:
      - ./data:/data
    restart: unless-stopped 
```

### PR DESCRIPTION
**Pull request by tonymmm1**
Fixes #889

### CODE REVIEW

**Comment by tonymmm1** [comment]
Just build the docker image on my test vm and the url fix seems to be fine after running the build image. 

logs:
```
minecraft    | [init] Changing ownership of /data to 1000 ...
minecraft    | [init] Running as uid=1000 gid=1000 with /data as 'drwxrwxr-x 2 1000 1000 6 May 24 00:25 /data'
minecraft    | [init] Resolved version given 1.12.2 into 1.12.2
minecraft    | [init] Resolving type given FORGE
minecraft    | [init] **********************************************************************
minecraft    | [init] WARNING: The image tag itzg/minecraft-server:java8 is recommended
minecraft    | [init]          since some mods require Java 8
minecraft    | [init]          Exception traces reporting ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader
minecraft    | [init]          can be fixed with java8
minecraft    | [init] **********************************************************************
minecraft    | [init] Checking Forge version information.
minecraft    | [init] Downloading 1.12.2-14.23.5.2854-1.12.2
minecraft    | [init] ...trying https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2854-1.12.2/forge-1.12.2-14.23.5.2854-1.12.2-installer.jar
minecraft    | curl: (22) The requested URL returned error: 404 
minecraft    | [init] ...trying https://maven.minecraftforge.net/net/minecraftforge/forge/1.12.2-14.23.5.2854/forge-1.12.2-14.23.5.2854-installer.jar
minecraft    | [init] Installing Forge 1.12.2-14.23.5.2854 using /tmp/forge-1.12.2-14.23.5.2854-installer.jar
minecraft    | JVM info: AdoptOpenJDK - 16.0.1 - 16.0.1+9
minecraft    | java.net.preferIPv4Stack=true
minecraft    | Found java version 16.0.1
```

**Comment by itzg** [comment]
I can't confirm the issue in #889 ; however, I'll test out this PR's change since it seems like a change for the better if it works more consistently.

**Review by itzg — APPROVED** [review]
Works great. Thanks!

**Comment by itzg** [comment]
This has been merged and pushed to the java8 image tags.

**Comment by tonymmm1** [comment]
@itzg Yeah no problem and thanks for the merge.

**Pull request merged**
